begin;
create extension if not exists pgtap with schema extensions;
set search_path=workspace,extensions,public;
select no_plan();
select is(has_function_privilege('anon','workspace_private.executive_task_definition(text)','execute'),false,'anon cannot invoke workspace_private.executive_task_definition(text)');
select is(has_function_privilege('authenticated','workspace_private.executive_task_definition(text)','execute'),false,'authenticated cannot invoke workspace_private.executive_task_definition(text)');
select is(has_function_privilege('anon','workspace_private.executive_schema_v1(text)','execute'),false,'anon cannot invoke workspace_private.executive_schema_v1(text)');
select is(has_function_privilege('authenticated','workspace_private.executive_schema_v1(text)','execute'),false,'authenticated cannot invoke workspace_private.executive_schema_v1(text)');
select is(has_function_privilege('anon','workspace_private.executive_schema(text)','execute'),false,'anon cannot invoke workspace_private.executive_schema(text)');
select is(has_function_privilege('authenticated','workspace_private.executive_schema(text)','execute'),false,'authenticated cannot invoke workspace_private.executive_schema(text)');
select is(has_function_privilege('anon','workspace_private.executive_reference_key(jsonb)','execute'),false,'anon cannot invoke workspace_private.executive_reference_key(jsonb)');
select is(has_function_privilege('authenticated','workspace_private.executive_reference_key(jsonb)','execute'),false,'authenticated cannot invoke workspace_private.executive_reference_key(jsonb)');
select is(has_function_privilege('anon','workspace_private.validate_executive_v1(text,jsonb)','execute'),false,'anon cannot invoke workspace_private.validate_executive_v1(text,jsonb)');
select is(has_function_privilege('authenticated','workspace_private.validate_executive_v1(text,jsonb)','execute'),false,'authenticated cannot invoke workspace_private.validate_executive_v1(text,jsonb)');
select is(has_function_privilege('anon','workspace_private.validate_executive(text,jsonb)','execute'),false,'anon cannot invoke workspace_private.validate_executive(text,jsonb)');
select is(has_function_privilege('authenticated','workspace_private.validate_executive(text,jsonb)','execute'),false,'authenticated cannot invoke workspace_private.validate_executive(text,jsonb)');
select is(has_function_privilege('anon','workspace_private.executive_task_allowed(uuid,text)','execute'),false,'anon cannot invoke workspace_private.executive_task_allowed(uuid,text)');
select is(has_function_privilege('authenticated','workspace_private.executive_task_allowed(uuid,text)','execute'),false,'authenticated cannot invoke workspace_private.executive_task_allowed(uuid,text)');
select is(has_function_privilege('anon','workspace_private.executive_change_source_permissions(jsonb,jsonb,integer,uuid,boolean,boolean,text)','execute'),false,'anon cannot invoke workspace_private.executive_change_source_permissions(jsonb,jsonb,integer,uuid,boolean,boolean,text)');
select is(has_function_privilege('authenticated','workspace_private.executive_change_source_permissions(jsonb,jsonb,integer,uuid,boolean,boolean,text)','execute'),false,'authenticated cannot invoke workspace_private.executive_change_source_permissions(jsonb,jsonb,integer,uuid,boolean,boolean,text)');
select is(has_function_privilege('anon','workspace_private.executive_task_metadata(text,uuid)','execute'),false,'anon cannot invoke workspace_private.executive_task_metadata(text,uuid)');
select is(has_function_privilege('authenticated','workspace_private.executive_task_metadata(text,uuid)','execute'),false,'authenticated cannot invoke workspace_private.executive_task_metadata(text,uuid)');
select is(has_function_privilege('anon','workspace_private.executive_task_source_records(text,uuid)','execute'),false,'anon cannot invoke workspace_private.executive_task_source_records(text,uuid)');
select is(has_function_privilege('authenticated','workspace_private.executive_task_source_records(text,uuid)','execute'),false,'authenticated cannot invoke workspace_private.executive_task_source_records(text,uuid)');
select is(has_function_privilege('anon','workspace_private.executive_source_record_v1(jsonb)','execute'),false,'anon cannot invoke workspace_private.executive_source_record_v1(jsonb)');
select is(has_function_privilege('authenticated','workspace_private.executive_source_record_v1(jsonb)','execute'),false,'authenticated cannot invoke workspace_private.executive_source_record_v1(jsonb)');
select is(has_function_privilege('anon','workspace_private.executive_source_record(jsonb)','execute'),false,'anon cannot invoke workspace_private.executive_source_record(jsonb)');
select is(has_function_privilege('authenticated','workspace_private.executive_source_record(jsonb)','execute'),false,'authenticated cannot invoke workspace_private.executive_source_record(jsonb)');
select is(has_function_privilege('anon','workspace_private.executive_scope_state(uuid,text,text)','execute'),false,'anon cannot invoke workspace_private.executive_scope_state(uuid,text,text)');
select is(has_function_privilege('authenticated','workspace_private.executive_scope_state(uuid,text,text)','execute'),false,'authenticated cannot invoke workspace_private.executive_scope_state(uuid,text,text)');
select is(has_function_privilege('anon','workspace_private.executive_source_cursor(jsonb)','execute'),false,'anon cannot invoke workspace_private.executive_source_cursor(jsonb)');
select is(has_function_privilege('authenticated','workspace_private.executive_source_cursor(jsonb)','execute'),false,'authenticated cannot invoke workspace_private.executive_source_cursor(jsonb)');
select is(has_function_privilege('anon','workspace.executive_get_source_permissions_v2()','execute'),false,'anonymous bridge denied: workspace.executive_get_source_permissions_v2()');
select is(has_function_privilege('authenticated','workspace.executive_get_source_permissions_v2()','execute'),true,'authenticated guarded bridge: workspace.executive_get_source_permissions_v2()');
select ok((select prosecdef from pg_proc where oid='workspace.executive_get_source_permissions_v2()'::regprocedure),'guarded owner rights: workspace.executive_get_source_permissions_v2()');
select is(has_function_privilege('anon','workspace.executive_set_source_permissions_v2(jsonb,jsonb,integer,uuid,boolean,boolean,text)','execute'),false,'anonymous bridge denied: workspace.executive_set_source_permissions_v2(jsonb,jsonb,integer,uuid,boolean,boolean,text)');
select is(has_function_privilege('authenticated','workspace.executive_set_source_permissions_v2(jsonb,jsonb,integer,uuid,boolean,boolean,text)','execute'),true,'authenticated guarded bridge: workspace.executive_set_source_permissions_v2(jsonb,jsonb,integer,uuid,boolean,boolean,text)');
select ok((select prosecdef from pg_proc where oid='workspace.executive_set_source_permissions_v2(jsonb,jsonb,integer,uuid,boolean,boolean,text)'::regprocedure),'guarded owner rights: workspace.executive_set_source_permissions_v2(jsonb,jsonb,integer,uuid,boolean,boolean,text)');
select is(has_function_privilege('anon','workspace.executive_find_sources(text,text,text,text,integer)','execute'),false,'anonymous bridge denied: workspace.executive_find_sources(text,text,text,text,integer)');
select is(has_function_privilege('authenticated','workspace.executive_find_sources(text,text,text,text,integer)','execute'),true,'authenticated guarded bridge: workspace.executive_find_sources(text,text,text,text,integer)');
select ok((select prosecdef from pg_proc where oid='workspace.executive_find_sources(text,text,text,text,integer)'::regprocedure),'guarded owner rights: workspace.executive_find_sources(text,text,text,text,integer)');
select is(has_function_privilege('anon','workspace.executive_review_attention(date,integer,integer)','execute'),false,'anonymous bridge denied: workspace.executive_review_attention(date,integer,integer)');
select is(has_function_privilege('authenticated','workspace.executive_review_attention(date,integer,integer)','execute'),true,'authenticated guarded bridge: workspace.executive_review_attention(date,integer,integer)');
select ok((select prosecdef from pg_proc where oid='workspace.executive_review_attention(date,integer,integer)'::regprocedure),'guarded owner rights: workspace.executive_review_attention(date,integer,integer)');
select throws_ok($$select workspace.executive_review_attention(current_date,0,25)$$,'42501',null,'attention needs verified identity');
select throws_ok($$select workspace.executive_find_sources('nonprofit.roadmap','task','',null,20)$$,'42501',null,'task catalog needs verified identity');
select throws_ok($$select workspace.executive_get_source_permissions_v2()$$,'42501',null,'permission view needs verified identity');
select throws_ok($$select workspace.executive_set_source_permissions_v2('[]','[]',0,gen_random_uuid(),true,true,'task-metadata-v1')$$,'42501',null,'permission changes need verified native identity');
select ok((select relrowsecurity from pg_class where oid='workspace_private.executive_source_permissions'::regclass),'permission RLS retained');
select ok((select relrowsecurity from pg_class where oid='workspace_private.executive_source_permission_versions'::regclass),'permission audit RLS retained');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permission_versions','SELECT'),false,'permission audit inaccessible directly');
select * from finish();
rollback;
