begin;
create extension if not exists pgtap with schema extensions;
set search_path=workspace,extensions,public;
select no_plan();
select is(has_table_privilege('anon','workspace_private.executive_documents','select'),false,'executive_documents: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.executive_documents','insert'),false,'executive_documents: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.executive_documents','update'),false,'executive_documents: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.executive_documents','delete'),false,'executive_documents: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.executive_documents','select'),false,'executive_documents: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.executive_documents','insert'),false,'executive_documents: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.executive_documents','update'),false,'executive_documents: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.executive_documents','delete'),false,'executive_documents: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.executive_documents'::regclass),'executive_documents: RLS enabled');
select is(has_table_privilege('anon','workspace_private.executive_versions','select'),false,'executive_versions: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.executive_versions','insert'),false,'executive_versions: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.executive_versions','update'),false,'executive_versions: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.executive_versions','delete'),false,'executive_versions: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.executive_versions','select'),false,'executive_versions: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.executive_versions','insert'),false,'executive_versions: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.executive_versions','update'),false,'executive_versions: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.executive_versions','delete'),false,'executive_versions: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.executive_versions'::regclass),'executive_versions: RLS enabled');
select is(has_table_privilege('anon','workspace_private.executive_proposals','select'),false,'executive_proposals: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.executive_proposals','insert'),false,'executive_proposals: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.executive_proposals','update'),false,'executive_proposals: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.executive_proposals','delete'),false,'executive_proposals: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.executive_proposals','select'),false,'executive_proposals: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.executive_proposals','insert'),false,'executive_proposals: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.executive_proposals','update'),false,'executive_proposals: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.executive_proposals','delete'),false,'executive_proposals: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.executive_proposals'::regclass),'executive_proposals: RLS enabled');
select is(has_table_privilege('anon','workspace_private.executive_source_permissions','select'),false,'executive_source_permissions: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.executive_source_permissions','insert'),false,'executive_source_permissions: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.executive_source_permissions','update'),false,'executive_source_permissions: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.executive_source_permissions','delete'),false,'executive_source_permissions: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permissions','select'),false,'executive_source_permissions: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permissions','insert'),false,'executive_source_permissions: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permissions','update'),false,'executive_source_permissions: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permissions','delete'),false,'executive_source_permissions: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.executive_source_permissions'::regclass),'executive_source_permissions: RLS enabled');
select is(has_table_privilege('anon','workspace_private.executive_source_permission_versions','select'),false,'executive_source_permission_versions: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.executive_source_permission_versions','insert'),false,'executive_source_permission_versions: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.executive_source_permission_versions','update'),false,'executive_source_permission_versions: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.executive_source_permission_versions','delete'),false,'executive_source_permission_versions: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permission_versions','select'),false,'executive_source_permission_versions: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permission_versions','insert'),false,'executive_source_permission_versions: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permission_versions','update'),false,'executive_source_permission_versions: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.executive_source_permission_versions','delete'),false,'executive_source_permission_versions: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.executive_source_permission_versions'::regclass),'executive_source_permission_versions: RLS enabled');
select is(has_function_privilege('anon','workspace.executive_get_document(text,uuid)','execute'),false,'executive_get_document(text,uuid): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_get_document(text,uuid)','execute'),true,'executive_get_document(text,uuid): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_search_documents(text,text,integer,integer)','execute'),false,'executive_search_documents(text,text,integer,integer): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_search_documents(text,text,integer,integer)','execute'),true,'executive_search_documents(text,text,integer,integer): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_save_document(text,uuid,integer,uuid,jsonb,boolean)','execute'),false,'executive_save_document(text,uuid,integer,uuid,jsonb,boolean): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_save_document(text,uuid,integer,uuid,jsonb,boolean)','execute'),true,'executive_save_document(text,uuid,integer,uuid,jsonb,boolean): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_propose_document(text,uuid,integer,uuid,jsonb,text,text,text)','execute'),false,'executive_propose_document(text,uuid,integer,uuid,jsonb,text,text,text): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_propose_document(text,uuid,integer,uuid,jsonb,text,text,text)','execute'),true,'executive_propose_document(text,uuid,integer,uuid,jsonb,text,text,text): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_list_proposals(text,integer,text)','execute'),false,'executive_list_proposals(text,integer,text): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_list_proposals(text,integer,text)','execute'),true,'executive_list_proposals(text,integer,text): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_decide_proposal(uuid,integer,text,boolean)','execute'),false,'executive_decide_proposal(uuid,integer,text,boolean): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_decide_proposal(uuid,integer,text,boolean)','execute'),true,'executive_decide_proposal(uuid,integer,text,boolean): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_document_history(text,uuid)','execute'),false,'executive_document_history(text,uuid): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_document_history(text,uuid)','execute'),true,'executive_document_history(text,uuid): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_get_source_permissions()','execute'),false,'executive_get_source_permissions(): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_get_source_permissions()','execute'),true,'executive_get_source_permissions(): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_set_source_permissions(jsonb,integer,uuid,boolean)','execute'),false,'executive_set_source_permissions(jsonb,integer,uuid,boolean): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_set_source_permissions(jsonb,integer,uuid,boolean)','execute'),true,'executive_set_source_permissions(jsonb,integer,uuid,boolean): authenticated execution privilege');
select is(has_function_privilege('anon','workspace.executive_resolve_references(jsonb)','execute'),false,'executive_resolve_references(jsonb): anon execution privilege');
select is(has_function_privilege('authenticated','workspace.executive_resolve_references(jsonb)','execute'),true,'executive_resolve_references(jsonb): authenticated execution privilege');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='workspace_private' and (p.proname like 'executive_%' or p.proname in ('require_executive','require_executive_any','validate_executive','validate_executive_references','normalize_executive')) and has_function_privilege('anon',p.oid,'execute')),0,'all Executive private helpers deny direct anon execution');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='workspace_private' and (p.proname like 'executive_%' or p.proname in ('require_executive','require_executive_any','validate_executive','validate_executive_references','normalize_executive')) and has_function_privilege('authenticated',p.oid,'execute')),0,'all Executive private helpers deny direct authenticated execution');
select * from finish();
rollback;
