begin;
create extension if not exists pgtap with schema extensions;
set search_path=workspace,extensions,public;
select no_plan();
select is(has_table_privilege('anon','workspace_private.investor_documents','select'),false,'investor_documents: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.investor_documents','insert'),false,'investor_documents: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.investor_documents','update'),false,'investor_documents: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.investor_documents','delete'),false,'investor_documents: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.investor_documents','select'),false,'investor_documents: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.investor_documents','insert'),false,'investor_documents: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.investor_documents','update'),false,'investor_documents: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.investor_documents','delete'),false,'investor_documents: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.investor_documents'::regclass),'investor_documents: RLS enabled');
select is(has_table_privilege('anon','workspace_private.investor_versions','select'),false,'investor_versions: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.investor_versions','insert'),false,'investor_versions: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.investor_versions','update'),false,'investor_versions: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.investor_versions','delete'),false,'investor_versions: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.investor_versions','select'),false,'investor_versions: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.investor_versions','insert'),false,'investor_versions: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.investor_versions','update'),false,'investor_versions: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.investor_versions','delete'),false,'investor_versions: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.investor_versions'::regclass),'investor_versions: RLS enabled');
select is(has_table_privilege('anon','workspace_private.investor_proposals','select'),false,'investor_proposals: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.investor_proposals','insert'),false,'investor_proposals: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.investor_proposals','update'),false,'investor_proposals: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.investor_proposals','delete'),false,'investor_proposals: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.investor_proposals','select'),false,'investor_proposals: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.investor_proposals','insert'),false,'investor_proposals: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.investor_proposals','update'),false,'investor_proposals: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.investor_proposals','delete'),false,'investor_proposals: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.investor_proposals'::regclass),'investor_proposals: RLS enabled');
select is(has_table_privilege('anon','workspace_private.investor_source_clock','select'),false,'investor_source_clock: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.investor_source_clock','insert'),false,'investor_source_clock: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.investor_source_clock','update'),false,'investor_source_clock: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.investor_source_clock','delete'),false,'investor_source_clock: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.investor_source_clock','select'),false,'investor_source_clock: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.investor_source_clock','insert'),false,'investor_source_clock: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.investor_source_clock','update'),false,'investor_source_clock: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.investor_source_clock','delete'),false,'investor_source_clock: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.investor_source_clock'::regclass),'investor_source_clock: RLS enabled');
select is(has_table_privilege('anon','workspace_private.investor_source_budgets','select'),false,'investor_source_budgets: anon direct select denied');
select is(has_table_privilege('anon','workspace_private.investor_source_budgets','insert'),false,'investor_source_budgets: anon direct insert denied');
select is(has_table_privilege('anon','workspace_private.investor_source_budgets','update'),false,'investor_source_budgets: anon direct update denied');
select is(has_table_privilege('anon','workspace_private.investor_source_budgets','delete'),false,'investor_source_budgets: anon direct delete denied');
select is(has_table_privilege('authenticated','workspace_private.investor_source_budgets','select'),false,'investor_source_budgets: authenticated direct select denied');
select is(has_table_privilege('authenticated','workspace_private.investor_source_budgets','insert'),false,'investor_source_budgets: authenticated direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.investor_source_budgets','update'),false,'investor_source_budgets: authenticated direct update denied');
select is(has_table_privilege('authenticated','workspace_private.investor_source_budgets','delete'),false,'investor_source_budgets: authenticated direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.investor_source_budgets'::regclass),'investor_source_budgets: RLS enabled');
select is(has_function_privilege('anon','workspace.investor_get_document(text,uuid)','execute'),false,'investor_get_document(text,uuid): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_get_document(text,uuid)','execute'),true,'investor_get_document(text,uuid): authenticated callers use guarded RPC');
select is(has_function_privilege('anon','workspace.investor_search_documents(text,text,integer,integer)','execute'),false,'investor_search_documents(text,text,integer,integer): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_search_documents(text,text,integer,integer)','execute'),true,'investor_search_documents(text,text,integer,integer): authenticated callers use guarded RPC');
select is(has_function_privilege('anon','workspace.investor_save_document(text,uuid,integer,uuid,jsonb,boolean)','execute'),false,'investor_save_document(text,uuid,integer,uuid,jsonb,boolean): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_save_document(text,uuid,integer,uuid,jsonb,boolean)','execute'),true,'investor_save_document(text,uuid,integer,uuid,jsonb,boolean): authenticated callers use guarded RPC');
select is(has_function_privilege('anon','workspace.investor_propose_document(text,uuid,integer,uuid,jsonb,text,text,text)','execute'),false,'investor_propose_document(text,uuid,integer,uuid,jsonb,text,text,text): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_propose_document(text,uuid,integer,uuid,jsonb,text,text,text)','execute'),true,'investor_propose_document(text,uuid,integer,uuid,jsonb,text,text,text): authenticated callers use guarded RPC');
select is(has_function_privilege('anon','workspace.investor_list_proposals(text,integer,text)','execute'),false,'investor_list_proposals(text,integer,text): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_list_proposals(text,integer,text)','execute'),true,'investor_list_proposals(text,integer,text): authenticated callers use guarded RPC');
select is(has_function_privilege('anon','workspace.investor_decide_proposal(uuid,integer,text,boolean)','execute'),false,'investor_decide_proposal(uuid,integer,text,boolean): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_decide_proposal(uuid,integer,text,boolean)','execute'),true,'investor_decide_proposal(uuid,integer,text,boolean): authenticated callers use guarded RPC');
select is(has_function_privilege('anon','workspace.investor_document_history(text,uuid)','execute'),false,'investor_document_history(text,uuid): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_document_history(text,uuid)','execute'),true,'investor_document_history(text,uuid): authenticated callers use guarded RPC');
select is(has_function_privilege('anon','workspace.investor_next_moves()','execute'),false,'investor_next_moves(): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_next_moves()','execute'),true,'investor_next_moves(): authenticated callers use guarded RPC');
select is(has_function_privilege('anon','workspace.investor_public_source_access(boolean)','execute'),false,'investor_public_source_access(boolean): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace.investor_public_source_access(boolean)','execute'),true,'investor_public_source_access(boolean): authenticated callers use guarded RPC');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='workspace_private' and (p.proname like 'investor_%' or p.proname in ('require_investor','validate_investor','normalize_investor')) and has_function_privilege('authenticated',p.oid,'execute')),0,'all Investor private helpers deny direct authenticated execution');
select * from finish();
rollback;
