begin;
create extension if not exists pgtap with schema extensions;
set search_path=workspace,extensions,public;
select no_plan();
select is(has_table_privilege('authenticated','workspace_private.ministry_documents','select'),false,'private documents cannot be selected directly');
select is(has_table_privilege('authenticated','workspace_private.ministry_documents','insert'),false,'canonical content cannot be inserted directly');
select is(has_table_privilege('authenticated','workspace_private.ministry_documents','update'),false,'canonical content cannot be updated directly');
select is(has_table_privilege('authenticated','workspace_private.ministry_document_versions','select'),false,'private revisions cannot be selected directly');
select is(has_table_privilege('authenticated','workspace_private.ministry_document_versions','insert'),false,'revision origin cannot be forged directly');
select is(has_table_privilege('authenticated','workspace_private.ministry_document_versions','delete'),false,'originals cannot be deleted directly');
select is(has_table_privilege('authenticated','workspace_private.ministry_proposals','select'),false,'proposals cannot be selected directly');
select is(has_table_privilege('authenticated','workspace_private.ministry_proposals','update'),false,'proposal approval cannot be forged directly');
select is(has_table_privilege('authenticated','workspace_private.ministry_proposals','delete'),false,'proposals cannot be erased directly');
select ok((select relrowsecurity from pg_class where oid='workspace_private.ministry_documents'::regclass),'document RLS enabled');
select ok((select relrowsecurity from pg_class where oid='workspace_private.ministry_document_versions'::regclass),'version RLS enabled');
select ok((select relrowsecurity from pg_class where oid='workspace_private.ministry_proposals'::regclass),'proposal RLS enabled');
select is(has_function_privilege('anon','workspace.ministry_get_document(text,uuid)','execute'),false,'anonymous document access denied');
select is(has_function_privilege('anon','workspace.ministry_save_document(text,uuid,integer,uuid,jsonb,boolean)','execute'),false,'anonymous canonical write denied');
select is(has_function_privilege('anon','workspace.ministry_propose_research(uuid,integer,uuid,jsonb,text,text)','execute'),false,'anonymous proposal write denied');
select is(has_function_privilege('authenticated','workspace_private.require_ministry(text,boolean)','execute'),false,'callers cannot choose a tenant via helper');
select is(has_function_privilege('authenticated','workspace_private.ministry_document_result(workspace_private.ministry_documents)','execute'),false,'callers cannot bypass the authorized reader');
select is(has_function_privilege('authenticated','workspace_private.ministry_proposal_result(workspace_private.ministry_proposals)','execute'),false,'callers cannot bypass proposal ownership');
select * from finish();
rollback;
