begin;
select no_plan();
select ok(not has_table_privilege(r,'workspace_private.'||d||t,p),r||' cannot '||p||' '||d||t)
from unnest(array['anon','authenticated'])r cross join unnest(array['ministry','nonprofit','investor','executive'])d
cross join unnest(array['_editor_drafts','_editor_draft_receipts'])t cross join unnest(array['select','insert','update','delete'])p;
select ok((select relrowsecurity from pg_class where oid=('workspace_private.'||d||t)::regclass),d||t||' has RLS')
from unnest(array['ministry','nonprofit','investor','executive'])d cross join unnest(array['_editor_drafts','_editor_draft_receipts'])t;
select ok(not has_function_privilege(r,s,'execute'),r||' cannot invoke '||s)
from unnest(array['anon','authenticated'])r cross join unnest(array['workspace_private.editor_recovery_schema(text,text)',
'workspace_private.editor_recovery_validate(jsonb,jsonb,integer)','workspace_private.require_editor_target(jsonb)',
'workspace_private.editor_source_revision(uuid,jsonb)','workspace_private.editor_draft_snapshot(uuid,jsonb)'])s;
select ok(not has_function_privilege('anon',s,'execute'),'anonymous cannot invoke '||s)
from unnest(array['workspace.native_editor_draft(jsonb)','workspace.native_change_editor_draft(jsonb)'])s;
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data) values
('15111111-1111-4111-8111-111111111111','authenticated','authenticated','p15.owner@example.invalid','{}','{}'),
('15222222-2222-4222-8222-222222222222','authenticated','authenticated','p15.other@example.invalid','{}','{}');
insert into workspace.workspaces(id,workspace_type,name,owner_user_id) values
('15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','personal','Fictional P15 owner','15111111-1111-4111-8111-111111111111'),
('15bbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','personal','Fictional P15 other','15222222-2222-4222-8222-222222222222');
insert into workspace.workspace_memberships(workspace_id,user_id,role,status) values
('15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','15111111-1111-4111-8111-111111111111','owner','active'),
('15bbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','15222222-2222-4222-8222-222222222222','owner','active');
insert into workspace.personal_plans(workspace_id,user_id,plan_key) values
('15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','15111111-1111-4111-8111-111111111111','personal'),
('15bbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','15222222-2222-4222-8222-222222222222','personal');
update workspace.plan_capabilities set enabled=true where plan_key='personal' and capability_key='core_workspace';
insert into workspace.bundle_entitlements(workspace_id,beneficiary_user_id,bundle_key,source,source_reference)
select '15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','15111111-1111-4111-8111-111111111111',b,'operator_assignment','p15-owner-'||b
from unnest(array['ministry','nonprofit_founder','investor','executive'])b;
insert into workspace.bundle_entitlements(workspace_id,beneficiary_user_id,bundle_key,source,source_reference)
values('15bbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','15222222-2222-4222-8222-222222222222','workspace_experience','operator_assignment','p15-other-experience');
create temp table p15_cases(domain text,kind text,blank jsonb,valid jsonb,target jsonb,save_input jsonb,valid_input jsonb,commit_input jsonb,committed jsonb);
insert into p15_cases(domain,kind,blank,valid,target) values
('ministry','profile','{"traditionContext":"","preferredTranslations":[],"interpretiveNotes":"","dialoguePreferences":"","positions":[]}'::jsonb,'{"traditionContext":"","preferredTranslations":[],"interpretiveNotes":"","dialoguePreferences":"","positions":[]}'::jsonb,'{"domain":"ministry","kind":"profile","documentId":null}'::jsonb),
('ministry','research','{"title":"","question":"","passage":"","audience":"","dueDate":null,"status":"researching","sources":[],"notes":[],"teachingOutline":""}'::jsonb,'{"title":"Fictional recovery ministry research","question":"Fictional recovery acceptance","passage":"","audience":"","dueDate":null,"status":"researching","sources":[],"notes":[],"teachingOutline":""}'::jsonb,'{"domain":"ministry","kind":"research","documentId":null}'::jsonb),
('ministry','archive','{"title":"","author":"","resourceType":"sermon","deliveredDate":null,"scriptureReferences":[],"topics":[],"audience":"","summary":"","bodyText":"","sourceLabel":"","sourceUrl":null,"status":"active"}'::jsonb,'{"title":"Fictional recovery ministry archive","author":"","resourceType":"sermon","deliveredDate":null,"scriptureReferences":[],"topics":[],"audience":"","summary":"","bodyText":"","sourceLabel":"Fictional recovery acceptance","sourceUrl":null,"status":"active"}'::jsonb,'{"domain":"ministry","kind":"archive","documentId":null}'::jsonb),
('nonprofit','plan','{"title":"","mission":"","jurisdiction":"","status":"active","targetDate":null,"milestones":[]}'::jsonb,'{"title":"Fictional recovery nonprofit plan","mission":"","jurisdiction":"","status":"active","targetDate":null,"milestones":[]}'::jsonb,'{"domain":"nonprofit","kind":"plan","documentId":null}'::jsonb),
('nonprofit','partner','{"title":"","role":"partner","contactName":"","contactEmail":"","stage":"identified","owner":"","nextAction":"","followupDate":null,"lastContactDate":null,"notes":"","outreachDraft":""}'::jsonb,'{"title":"Fictional recovery nonprofit partner","role":"partner","contactName":"","contactEmail":"","stage":"identified","owner":"","nextAction":"","followupDate":null,"lastContactDate":null,"notes":"","outreachDraft":""}'::jsonb,'{"domain":"nonprofit","kind":"partner","documentId":null}'::jsonb),
('nonprofit','meeting','{"title":"","scheduledDate":null,"localTime":"","timeZone":"","location":"","participants":[],"status":"scheduled","agenda":"","notes":"","decisions":[],"actions":[]}'::jsonb,'{"title":"Fictional recovery nonprofit meeting","scheduledDate":null,"localTime":"","timeZone":"UTC","location":"","participants":[],"status":"scheduled","agenda":"","notes":"","decisions":[],"actions":[]}'::jsonb,'{"domain":"nonprofit","kind":"meeting","documentId":null}'::jsonb),
('nonprofit','research','{"title":"","category":"regulatory","jurisdiction":"","question":"","status":"open","reviewDate":null,"owner":"","sources":[],"interpretation":"","uncertainty":"Not yet researched. Applicability and current requirements need verification.","requiredAction":"","professionalReview":"Identify the appropriate qualified professional to review applicability before acting.","epistemicState":"inferred"}'::jsonb,'{"title":"Fictional recovery nonprofit research","category":"regulatory","jurisdiction":"Fictional recovery acceptance","question":"Fictional recovery acceptance","status":"open","reviewDate":null,"owner":"","sources":[],"interpretation":"","uncertainty":"Not yet researched. Applicability and current requirements need verification.","requiredAction":"","professionalReview":"Identify the appropriate qualified professional to review applicability before acting.","epistemicState":"inferred"}'::jsonb,'{"domain":"nonprofit","kind":"research","documentId":null}'::jsonb),
('investor','watchlist','{"title":"","status":"draft","asOfDate":"2026-09-15","reviewDate":null,"purpose":"","entries":[]}'::jsonb,'{"title":"Fictional recovery investor watchlist","status":"draft","asOfDate":"2026-09-15","reviewDate":null,"purpose":"","entries":[]}'::jsonb,'{"domain":"investor","kind":"watchlist","documentId":null}'::jsonb),
('investor','thesis','{"title":"","status":"draft","asOfDate":"2026-09-15","reviewDate":null,"sources":[],"claims":[],"catalysts":[],"uncertainty":"Not yet researched. Source coverage, freshness and applicability need review.","nextQuestion":"","instrument":{"name":"","ticker":"","exchange":"","cik":""},"question":"","thesis":"","horizon":"","stance":"investigating","confidence":null,"changeAssessment":"not_reviewed","changeReason":"","invalidations":[],"scenarioMode":"draft","scenarios":[]}'::jsonb,'{"title":"Fictional recovery investor thesis","status":"draft","asOfDate":"2026-09-15","reviewDate":null,"sources":[],"claims":[],"catalysts":[],"uncertainty":"Not yet researched. Source coverage, freshness and applicability need review.","nextQuestion":"","instrument":{"name":"Fictional recovery acceptance","ticker":"","exchange":"","cik":""},"question":"Fictional recovery acceptance","thesis":"Fictional recovery acceptance","horizon":"Fictional recovery acceptance","stance":"investigating","confidence":null,"changeAssessment":"not_reviewed","changeReason":"","invalidations":[],"scenarioMode":"draft","scenarios":[]}'::jsonb,'{"domain":"investor","kind":"thesis","documentId":null}'::jsonb),
('investor','filing','{"title":"","status":"draft","asOfDate":"2026-09-15","reviewDate":null,"sources":[],"claims":[],"catalysts":[],"uncertainty":"Not yet researched. Source coverage, freshness and applicability need review.","nextQuestion":"","instrument":{"name":"","ticker":"","exchange":"","cik":""},"filerName":"","filerCik":"","form":"10-K","accession":"","filingUrl":"","filedDate":"2026-09-15","periodEnd":null,"amendmentOf":"","question":"","transactionDate":null,"transactionCodes":"","transactionFootnotes":"","plan10b51":"unknown","holdingsLimitations":""}'::jsonb,'{"title":"Fictional recovery investor filing","status":"draft","asOfDate":"2026-09-15","reviewDate":null,"sources":[],"claims":[],"catalysts":[],"uncertainty":"Not yet researched. Source coverage, freshness and applicability need review.","nextQuestion":"","instrument":{"name":"Fictional recovery acceptance","ticker":"","exchange":"","cik":""},"filerName":"Fictional recovery acceptance","filerCik":"","form":"10-K","accession":"","filingUrl":"https://example.invalid/fictional-filing","filedDate":"2026-09-15","periodEnd":null,"amendmentOf":"","question":"Fictional recovery acceptance","transactionDate":null,"transactionCodes":"","transactionFootnotes":"","plan10b51":"unknown","holdingsLimitations":""}'::jsonb,'{"domain":"investor","kind":"filing","documentId":null}'::jsonb),
('investor','brief','{"title":"","status":"draft","asOfDate":"2026-09-15","reviewDate":null,"sources":[],"claims":[],"catalysts":[],"uncertainty":"Not yet researched. Source coverage, freshness and applicability need review.","nextQuestion":"","scope":"","periodStart":"2026-09-15","periodEnd":"2026-09-15","summary":""}'::jsonb,'{"title":"Fictional recovery investor brief","status":"draft","asOfDate":"2026-09-15","reviewDate":null,"sources":[],"claims":[],"catalysts":[],"uncertainty":"Not yet researched. Source coverage, freshness and applicability need review.","nextQuestion":"","scope":"Fictional recovery acceptance","periodStart":"2026-09-15","periodEnd":"2026-09-15","summary":"Fictional recovery acceptance"}'::jsonb,'{"domain":"investor","kind":"brief","documentId":null}'::jsonb),
('executive','commitment','{"title":"","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"commitment","state":"open","owner":"","outcome":"","nextAction":"","dueDate":null,"followupDate":null,"completedOn":null,"blocker":""}'::jsonb,'{"title":"Fictional recovery executive commitment","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"commitment","state":"open","owner":"","outcome":"Fictional recovery acceptance","nextAction":"","dueDate":null,"followupDate":null,"completedOn":null,"blocker":""}'::jsonb,'{"domain":"executive","kind":"commitment","documentId":null}'::jsonb),
('executive','decision','{"title":"","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"decision","state":"open","question":"","owner":"","dueDate":null,"nextAction":"","options":[],"selectedOptionId":null,"decidedOn":null,"rationale":"","revisitTrigger":""}'::jsonb,'{"title":"Fictional recovery executive decision","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"decision","state":"open","question":"Fictional recovery acceptance","owner":"","dueDate":null,"nextAction":"","options":[],"selectedOptionId":null,"decidedOn":null,"rationale":"","revisitTrigger":""}'::jsonb,'{"domain":"executive","kind":"decision","documentId":null}'::jsonb),
('executive','meeting','{"title":"","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"meeting","state":"planned","objective":"","participants":[],"agenda":"","startsAt":null,"timeZone":"","durationMinutes":30,"agreement":"not_agreed","location":"","outcome":"","actions":[]}'::jsonb,'{"title":"Fictional recovery executive meeting","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"meeting","state":"planned","objective":"Fictional recovery acceptance","participants":[],"agenda":"","startsAt":null,"timeZone":"UTC","durationMinutes":30,"agreement":"not_agreed","location":"","outcome":"","actions":[]}'::jsonb,'{"domain":"executive","kind":"meeting","documentId":null}'::jsonb),
('executive','daily_brief','{"title":"","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"daily_brief","state":"draft","periodStart":"2026-09-15","periodEnd":"2026-09-15","focus":"","summary":"","observations":[],"actions":[],"reflection":""}'::jsonb,'{"title":"Fictional recovery executive daily_brief","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"daily_brief","state":"draft","periodStart":"2026-09-15","periodEnd":"2026-09-15","focus":"Fictional recovery acceptance","summary":"","observations":[],"actions":[],"reflection":""}'::jsonb,'{"domain":"executive","kind":"daily_brief","documentId":null}'::jsonb),
('executive','weekly_review','{"title":"","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"weekly_review","state":"draft","periodStart":"2026-09-09","periodEnd":"2026-09-15","focus":"","summary":"","observations":[],"actions":[],"reflection":""}'::jsonb,'{"title":"Fictional recovery executive weekly_review","notes":"","priority":"normal","reviewState":"user_stated","reviewDate":null,"references":[],"recordType":"weekly_review","state":"draft","periodStart":"2026-09-09","periodEnd":"2026-09-15","focus":"Fictional recovery acceptance","summary":"","observations":[],"actions":[],"reflection":""}'::jsonb,'{"domain":"executive","kind":"weekly_review","documentId":null}'::jsonb);
update p15_cases set save_input=jsonb_build_object('target',target,'operation','save','requestId',gen_random_uuid(),'expectedVersion',0,'schemaVersion',1,'baseRevision',0,'values',jsonb_build_object('data',blank,'ui','{}'::jsonb));
create temp table p15_cache(k text primary key,v jsonb);grant all on p15_cases,p15_cache to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"15111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
select is((workspace.native_editor_draft(target)->>'version')::int,0,domain||' '||kind||' starts without a draft') from p15_cases;
select is((workspace.native_change_editor_draft(save_input)->>'version')::int,1,domain||' '||kind||' preserves incomplete fields without Experience access') from p15_cases;
select is(workspace.native_editor_draft(target)->'values'->'data',blank,domain||' '||kind||' reads its exact private draft') from p15_cases;
select is((workspace.native_change_editor_draft(save_input)->>'version')::int,1,domain||' '||kind||' retry does not duplicate') from p15_cases;
select throws_ok($q$select workspace.native_change_editor_draft(save_input||jsonb_build_object('requestId',gen_random_uuid())) from p15_cases where domain='ministry' and kind='research'$q$,'40001',null::text,'stale tab cannot overwrite a saved working draft');
select throws_ok($q$select workspace.native_change_editor_draft(save_input||'{"baseRevision":1}'::jsonb) from p15_cases where domain='ministry' and kind='research'$q$,'40001',null::text,'same request ID cannot be reused for different input');
select throws_ok($q$select workspace.native_change_editor_draft(jsonb_build_object('target',target,'operation','commit','requestId',gen_random_uuid(),'expectedVersion',1,'confirm',true)) from p15_cases where domain='ministry' and kind='research'$q$,'22023',null::text,'incomplete working draft cannot bypass canonical validation');
select is((workspace.native_editor_draft(target)->>'version')::int,1,'failed canonical validation retains the draft') from p15_cases where domain='ministry' and kind='research';
reset role;
select is((select count(*)::int from workspace_private.ministry_documents where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),0,'drafts did not create Ministry records');
select is((select count(*)::int from workspace_private.nonprofit_documents where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),0,'drafts did not create Nonprofit records');
select is((select count(*)::int from workspace_private.investor_documents where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),0,'drafts did not create Investor records');
select is((select count(*)::int from workspace_private.executive_documents where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),0,'drafts did not create Executive records');
set local role authenticated;
update p15_cases set valid_input=save_input||jsonb_build_object('requestId',gen_random_uuid(),'expectedVersion',1,'values',jsonb_build_object('data',valid,'ui','{}'::jsonb));
select is((workspace.native_change_editor_draft(valid_input)->>'version')::int,2,domain||' '||kind||' saves the reviewed on-screen fields') from p15_cases;
update p15_cases set commit_input=jsonb_build_object('target',target,'operation','commit','requestId',gen_random_uuid(),'expectedVersion',2,'confirm',true);
select throws_ok($q$select workspace.native_change_editor_draft(commit_input||'{"confirm":false}'::jsonb) from p15_cases where domain='nonprofit' and kind='plan'$q$,'22023',null::text,'explicit client confirmation required');
update p15_cases set committed=workspace.native_change_editor_draft(commit_input);
select is(committed->'values','null'::jsonb,domain||' '||kind||' commit retires the working text atomically') from p15_cases;
select is((committed->'receipt'->>'committedRevision')::int,1,domain||' '||kind||' confirmed revision is recorded') from p15_cases;
select is(workspace.native_change_editor_draft(commit_input),committed,domain||' '||kind||' lost commit response retries exactly') from p15_cases;
select throws_ok($q$select workspace.native_change_editor_draft(save_input) from p15_cases where domain='ministry' and kind='research'$q$,'40001',null::text,'old autosave receipt cannot resurrect committed text');
select throws_ok($q$select workspace.native_change_editor_draft(save_input||jsonb_build_object('requestId',gen_random_uuid())) from p15_cases where domain='investor' and kind='thesis'$q$,'40001',null::text,'old new-record tab cannot recreate a retired draft');
insert into p15_cache select 'research_target',jsonb_set(target,'{documentId}',committed->'receipt'->'committedDocumentId') from p15_cases where domain='ministry' and kind='research';
insert into p15_cache select 'research_save',jsonb_build_object('target',(select v from p15_cache where k='research_target'),'operation','save','requestId',gen_random_uuid(),'expectedVersion',0,'schemaVersion',1,'baseRevision',1,'values',jsonb_build_object('data',valid||'{"question":"PRIVATE_UNFINISHED_QUESTION"}'::jsonb,'ui','{}'::jsonb))from p15_cases where domain='ministry' and kind='research';
select lives_ok($q$select workspace.native_change_editor_draft(v) from p15_cache where k='research_save'$q$,'existing-record draft preserves its base revision');
select lives_ok($q$select workspace.ministry_save_document('research',((select v from p15_cache where k='research_target')->>'documentId')::uuid,1,gen_random_uuid(),valid||'{"question":"Separate saved edit"}'::jsonb,true) from p15_cases where domain='ministry' and kind='research'$q$,'independent canonical change is retained');
select is((workspace.native_editor_draft(v)->>'currentRevision')::int,2,'recovery exposes source revision change without rebasing') from p15_cache where k='research_target';
select throws_ok($q$select workspace.native_change_editor_draft(jsonb_build_object('target',v,'operation','commit','requestId',gen_random_uuid(),'expectedVersion',1,'confirm',true))from p15_cache where k='research_target'$q$,'40001',null::text,'stale source cannot be overwritten by recovery commit');
insert into p15_cache select 'discard',jsonb_build_object('target',v,'operation','discard','requestId',gen_random_uuid(),'expectedVersion',1)from p15_cache where k='research_target';
insert into p15_cache select 'discard_receipt',workspace.native_change_editor_draft(v)from p15_cache where k='discard';
select is(workspace.native_change_editor_draft((select v from p15_cache where k='discard')),(select v from p15_cache where k='discard_receipt'),'lost discard response retries exactly');
select is(workspace.native_editor_draft(v)->'values','null'::jsonb,'discard removes private text')from p15_cache where k='research_target';
select throws_ok($q$select workspace.native_change_editor_draft(v)from p15_cache where k='research_save'$q$,'40001',null::text,'old autosave cannot resurrect discarded text');
select throws_ok($q$select workspace.native_editor_draft(v||'{"workspaceId":"15bbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"}'::jsonb)from p15_cache where k='research_target'$q$,'22023',null::text,'tenant spoofing rejected');
select throws_ok($q$select workspace.native_editor_draft(v||'{"kind":"archive"}'::jsonb)from p15_cache where k='research_target'$q$,'P0002',null::text,'same-domain wrong kind denied');
select throws_ok($q$select workspace.native_editor_draft(v||'{"domain":"nonprofit"}'::jsonb)from p15_cache where k='research_target'$q$,'P0002',null::text,'cross-domain document lookup denied');
insert into p15_cache select 'meeting_target',jsonb_set(target,'{documentId}',committed->'receipt'->'committedDocumentId') from p15_cases where domain='executive' and kind='meeting';
select lives_ok($q$select workspace.native_change_editor_draft(jsonb_build_object('target',(select v from p15_cache where k='meeting_target'),'operation','save','requestId',gen_random_uuid(),'expectedVersion',0,'schemaVersion',1,'baseRevision',1,'values',jsonb_build_object('data',valid,'ui','{"meetingTime":{"local":"2026-11-01T01:30","selection":"","pending":true},"availability":{"zone":"UTC","offered":[{"id":"15444444-4444-4444-8444-444444444444","start":"2026-11-02T09:00","end":"","startInstant":"","endInstant":""}],"available":[],"busy":[],"source":"","bufferMinutes":-1,"checkedAt":null,"context":"[]","pending":true}}'::jsonb)))from p15_cases where domain='executive' and kind='meeting'$q$,'unapplied ambiguous meeting time is recoverable');
select throws_ok($q$select workspace.native_change_editor_draft(jsonb_build_object('target',v,'operation','commit','requestId',gen_random_uuid(),'expectedVersion',1,'confirm',true))from p15_cache where k='meeting_target'$q$,'22023',null::text,'unapplied time and availability are not silently committed');
select throws_ok($q$select workspace.native_change_editor_draft(jsonb_build_object('target',(select v from p15_cache where k='meeting_target'),'operation','save','requestId',gen_random_uuid(),'expectedVersion',1,'schemaVersion',1,'baseRevision',1,'values',jsonb_build_object('data',valid,'ui','{"availability":{"zone":"UTC","offered":[{"id":"not-a-uuid","start":"","end":"","startInstant":"","endInstant":""}],"available":[],"busy":[],"source":"","bufferMinutes":0,"checkedAt":null,"context":"[]","pending":true}}'::jsonb)))from p15_cases where domain='executive' and kind='meeting'$q$,'22023',null::text,'direct RPC rejects malformed availability window identity');
select set_config('request.jwt.claims','{"sub":"15222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
select throws_ok($q$select workspace.native_editor_draft(target)from p15_cases where domain='ministry' and kind='research'$q$,'42501',null::text,'Experience alone does not grant domain draft access');
reset role;
insert into workspace.bundle_entitlements(workspace_id,beneficiary_user_id,bundle_key,source,source_reference)
select '15bbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','15222222-2222-4222-8222-222222222222',b,'operator_assignment','p15-other-'||b from unnest(array['ministry','nonprofit_founder','investor','executive'])b;
set local role authenticated;
select is((workspace.native_editor_draft(target)->>'version')::int,0,domain||' '||kind||' other owner has a separate empty slot')from p15_cases;
select throws_ok($q$select workspace.native_editor_draft(v)from p15_cache where k='research_target'$q$,'P0002',null::text,'another entitled owner cannot read private draft');
select throws_ok($q$select workspace.native_change_editor_draft(v)from p15_cache where k='research_save'$q$,'P0002',null::text,'another entitled owner cannot mutate private draft');
select set_config('request.jwt.claims','{"sub":"15111111-1111-4111-8111-111111111111","role":"authenticated","client_id":"15333333-3333-4333-8333-333333333333"}',true);
select throws_ok($q$select workspace.native_editor_draft(target)from p15_cases where domain='ministry' and kind='research'$q$,'42501',null::text,'OAuth assistant cannot read drafts');
select throws_ok($q$select workspace.native_change_editor_draft(commit_input)from p15_cases where domain='executive' and kind='commitment'$q$,'42501',null::text,'OAuth assistant cannot replay native approval');
select set_config('request.jwt.claims','{"sub":"15111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
reset role;
update workspace.bundle_entitlements set revoked_at=now(),revocation_reason='Fictional recovery revocation test'
where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and bundle_key='ministry';
set local role authenticated;
select throws_ok($q$select workspace.native_editor_draft(v)from p15_cache where k='research_target'$q$,'42501',null::text,'revoked source blocks recovery read');
select throws_ok($q$select workspace.native_change_editor_draft(v)from p15_cache where k='discard'$q$,'42501',null::text,'revoked source blocks receipt replay');
reset role;
select is((select count(*)::int from workspace_private.ministry_editor_drafts where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and values_json::text like '%PRIVATE_UNFINISHED_QUESTION%'),0,'discarded private text is absent from working rows');
select is((select count(*)::int from workspace_private.ministry_editor_draft_receipts where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and row_to_json(ministry_editor_draft_receipts)::text like '%PRIVATE_UNFINISHED_QUESTION%'),0,'retry ledger retains no private draft text');
select is((select count(*)::int from workspace_private.ministry_documents where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),3,'exactly three Ministry records; no duplicate commits');
select is((select count(*)::int from workspace_private.nonprofit_documents where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),4,'exactly four Nonprofit records; no duplicate commits');
select is((select count(*)::int from workspace_private.investor_documents where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),4,'exactly four Investor records; no duplicate commits');
select is((select count(*)::int from workspace_private.executive_documents where workspace_id='15aaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),5,'exactly five Executive records; no duplicate commits');
select * from finish();
rollback;
