begin;
create extension if not exists pgtap with schema extensions;
set search_path=workspace,extensions,public;
select no_plan();
select is(has_table_privilege('authenticated','workspace_private.nonprofit_documents','select'),false,'nonprofit_documents: direct select denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_documents','insert'),false,'nonprofit_documents: direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_documents','update'),false,'nonprofit_documents: direct update denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_documents','delete'),false,'nonprofit_documents: direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.nonprofit_documents'::regclass),'nonprofit_documents: RLS enabled');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_versions','select'),false,'nonprofit_versions: direct select denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_versions','insert'),false,'nonprofit_versions: direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_versions','update'),false,'nonprofit_versions: direct update denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_versions','delete'),false,'nonprofit_versions: direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.nonprofit_versions'::regclass),'nonprofit_versions: RLS enabled');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_proposals','select'),false,'nonprofit_proposals: direct select denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_proposals','insert'),false,'nonprofit_proposals: direct insert denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_proposals','update'),false,'nonprofit_proposals: direct update denied');
select is(has_table_privilege('authenticated','workspace_private.nonprofit_proposals','delete'),false,'nonprofit_proposals: direct delete denied');
select ok((select relrowsecurity from pg_class where oid='workspace_private.nonprofit_proposals'::regclass),'nonprofit_proposals: RLS enabled');
select is(has_function_privilege('anon','workspace.nonprofit_get_document(text,uuid)','execute'),false,'nonprofit_get_document(text,uuid): anonymous execution denied');
select is(has_function_privilege('anon','workspace.nonprofit_search_documents(text,text,integer,integer)','execute'),false,'nonprofit_search_documents(text,text,integer,integer): anonymous execution denied');
select is(has_function_privilege('anon','workspace.nonprofit_save_document(text,uuid,integer,uuid,jsonb,boolean)','execute'),false,'nonprofit_save_document(text,uuid,integer,uuid,jsonb,boolean): anonymous execution denied');
select is(has_function_privilege('anon','workspace.nonprofit_propose_document(text,uuid,integer,uuid,jsonb,text,text,text)','execute'),false,'nonprofit_propose_document(text,uuid,integer,uuid,jsonb,text,text,text): anonymous execution denied');
select is(has_function_privilege('anon','workspace.nonprofit_list_proposals(text,integer,text)','execute'),false,'nonprofit_list_proposals(text,integer,text): anonymous execution denied');
select is(has_function_privilege('anon','workspace.nonprofit_decide_proposal(uuid,integer,text,boolean)','execute'),false,'nonprofit_decide_proposal(uuid,integer,text,boolean): anonymous execution denied');
select is(has_function_privilege('anon','workspace.nonprofit_document_history(text,uuid)','execute'),false,'nonprofit_document_history(text,uuid): anonymous execution denied');
select is(has_function_privilege('anon','workspace.nonprofit_next_moves()','execute'),false,'nonprofit_next_moves(): anonymous execution denied');
select is(has_function_privilege('authenticated','workspace_private.require_nonprofit(text)','execute'),false,'require_nonprofit(text): helper bypass denied');
select is(has_function_privilege('authenticated','workspace_private.nonprofit_document_result(workspace_private.nonprofit_documents)','execute'),false,'nonprofit_document_result(workspace_private.nonprofit_documents): helper bypass denied');
select is(has_function_privilege('authenticated','workspace_private.nonprofit_proposal_result(workspace_private.nonprofit_proposals)','execute'),false,'nonprofit_proposal_result(workspace_private.nonprofit_proposals): helper bypass denied');
select is(has_function_privilege('authenticated','workspace_private.validate_nonprofit(text,jsonb)','execute'),false,'validate_nonprofit(text,jsonb): helper bypass denied');
select * from finish();
rollback;
