import { expect, test } from '@playwright/test';

test('a first native session survives reload and recovers a lost save reply', async ({ page, request }) => {
  test.skip(!process.env.SOTF_SYNTHETIC_HARNESS, 'Requires the isolated synthetic component server, never a live account.');
  await request.post('/__test/reset');
  await page.goto('/');
  await page.getByLabel('Where are you in the transition?').fill('Exploring over the next six months');
  await page.getByLabel('What is the most useful decision to work on?').fill('Which work gives me meaningful ownership?');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('What would you like to spend time actually doing?').fill('Resolve delivery decisions across teams');
  await page.getByLabel('What kind of working environment do you want?').fill('Decision authority and a sustainable pace');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('Possibility 1').fill('Program leadership');
  await page.getByLabel('Possibility 2').fill('Operations improvement');
  await page.getByRole('button', { name: 'Confirm these starting points' }).click();
  await expect(page.getByRole('heading', { name: 'Which work gives me meaningful ownership?' })).toBeVisible();
  await page.getByRole('button', { name: 'Assess an opportunity', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('Company', { exact: true }).fill('Fictional Northstar');
  await dialog.getByLabel('Role', { exact: true }).fill('Program Lead');
  await dialog.getByRole('button', { name: 'Save and examine the evidence' }).click();
  await page.getByRole('button', { name: 'Record my decision and next move' }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('My decision').selectOption('investigate');
  await dialog.getByLabel('Why?', { exact: true }).fill('Decision ownership is unresolved');
  await dialog.getByLabel('Next action, or what I am deliberately pausing').fill('Ask a practitioner which decisions I would own');
  await dialog.getByLabel('What would cause me to reconsider?').fill('A specific example of decision authority');
  await request.post('/__test/lose-next-reply');
  await dialog.getByRole('button', { name: 'Confirm and save', exact: true }).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Verify and recover the same step' }).click();
  await expect(page.getByRole('status')).toContainText('previous step was saved');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Which work gives me meaningful ownership?' })).toBeVisible();
  await page.getByRole('button', { name: 'Opportunities', exact: true }).click();
  await expect(page.getByText('Your recorded decision', { exact: false })).toBeVisible();
  await expect(page.getByText('Next: Ask a practitioner which decisions I would own', { exact: true })).toBeVisible();
  const saved = await request.get('/api/sotf', { headers: { authorization: 'Bearer synthetic-local-session' } });
  const result = await saved.json(); expect(result.state.revision).toBe(3); expect(result.state.opportunities).toHaveLength(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
