"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { commandSchema, DIMENSIONS, type Command, type PilotState } from "@/lib/sotf/contracts";
import styles from "./sotf.module.css";

export type Intent = "opportunity" | "evidence" | "decision" | "person" | "meeting" | "debrief" | "hypothesis" | "criteria" | "promise" | "resolve-promise" | "weekly" | "story" | "material" | "submission" | "interview" | "offer" | "accept-offer" | "close-chapter" | "action" | "action-result" | "requirement" | "application-outcome";
type Option = { value: string; label: string };
type Field = { name: string; label: string; value?: string; type?: string; options?: Option[]; multiple?: boolean; optional?: boolean; help?: string };
type Definition = { title: string; description: string; fields: Field[]; submit: string; build: (values: FormData) => unknown };
const options = (values: string[]): Option[] => values.map((value) => ({ value, label: value.replaceAll("_", " ") }));
const field = (name: string, label: string, value = "", extra: Partial<Field> = {}): Field => ({ name, label, value, ...extra });
const get = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const lines = (data: FormData, key: string) => get(data, key).split("\n").map((value) => value.trim()).filter(Boolean);
const optional = (data: FormData, key: string) => get(data, key) || undefined;
const fresh = () => crypto.randomUUID();
const linkFields = (state: PilotState): Field[] => [
  field("opportunityId", "Related opportunity", "", { optional: true, options: state.opportunities.map((item) => ({ value: item.id, label: item.company + " · " + item.role })) }),
  field("hypothesisId", "Direction this helps test", "", { optional: true, options: state.hypotheses.map((item) => ({ value: item.id, label: item.proposition })) })
];
const hypothesisValue = (data: FormData, id: string) => ({ id, proposition: get(data, "proposition"), whyPromising: get(data, "whyPromising"), assumptions: lines(data, "assumptions"), gaps: lines(data, "gaps"), nextExperiment: get(data, "nextExperiment"), reviewTrigger: get(data, "reviewTrigger"), confidenceExplanation: get(data, "confidenceExplanation"), status: get(data, "status") || "continue" });

function definition(intent: Intent, state: PilotState, recordId?: string): Definition {
  const selectedOpportunity = state.opportunities.find((item) => item.id === recordId || item.id === state.meetings.find((meeting) => meeting.id === recordId)?.opportunityId);
  const selectedPerson = state.people.find((item) => item.id === recordId);
  const selectedMeeting = state.meetings.find((item) => item.id === recordId);
  const selectedHypothesis = state.hypotheses.find((item) => item.id === recordId);
  const selectedAction = state.actions.find((item) => item.id === recordId);
  const opportunityOptions = state.opportunities.map((item) => ({ value: item.id, label: item.company + " · " + item.role }));
  const chooseOpportunity = field("opportunityId", "Opportunity", selectedOpportunity?.id, { options: opportunityOptions });
  const today = new Date().toISOString().slice(0, 10);
  const common = { description: "Review this ordinary transition information before saving. Protected Professional Context remains available only through its separately approved capability.", submit: "Confirm and save" };
  switch (intent) {
    case "opportunity": return { ...common, title: "Assess an opportunity", description: "Bring a role you are actually considering. The assessment begins with unknowns until you review evidence.", fields: [
      field("company", "Company"), field("role", "Role"), field("url", "Job URL", "", { type: "url", optional: true }), field("description", "Job description", "", { type: "textarea", optional: true, help: "Paste the relevant role description, or add it through your connected ChatGPT workflow." }),
      field("requirements", "Mandatory requirements — one per line", "", { type: "textarea", optional: true }), field("preferred", "Preferred qualifications — one per line", "", { type: "textarea", optional: true }), field("actualWork", "What would you actually do?", "", { type: "textarea", optional: true }), field("deadline", "Application deadline", "", { type: "date", optional: true }), linkFields(state)[1]
    ], submit: "Save and examine the evidence", build: (data) => ({ type: "record_opportunity", opportunity: { id: fresh(), company: get(data, "company"), role: get(data, "role"), url: optional(data, "url"), description: get(data, "description"), actualWork: get(data, "actualWork"), deadline: optional(data, "deadline"), hypothesisIds: get(data, "hypothesisId") ? [get(data, "hypothesisId")] : [], requirements: [...lines(data, "requirements").map((label) => ({ id: fresh(), label, category: "mandatory", mandatory: true })), ...lines(data, "preferred").map((label) => ({ id: fresh(), label, category: "preferred", mandatory: false }))] } }) };
    case "evidence": return { ...common, title: "Add evidence to review", description: "Keep the observation, its source, and your interpretation distinct. New evidence awaits review before it changes an assessment.", fields: [
      { ...chooseOpportunity, optional: true }, field("statement", "What does the evidence say?", "", { type: "textarea" }), field("kind", "Source type", "practitioner", { options: options(["job_post", "company_claim", "practitioner", "independent_reporting", "community", "fellow_report", "inference"]) }), field("reference", "Source name or reference"), field("url", "Source URL", "", { type: "url", optional: true }), field("observedAt", "Observed on", today, { type: "date" }), field("scope", "Where does this apply?", "", { help: "A specific role, team, location, company claim, or one person's account." }),
      field("direction", "Effect on the current question", "neutral", { options: options(["supporting", "conflicting", "neutral"]) }), field("reliability", "How strong is this evidence?", "medium", { options: options(["low", "medium", "high"]) }), field("dimension", "Fit dimension", "", { optional: true, options: Object.entries(DIMENSIONS).map(([value, label]) => ({ value, label })) }), field("criterionId", "Related confirmed criterion", "", { optional: true, options: state.criteria.map((item) => ({ value: item.id, label: item.label })) }), field("score", "Fit judgment, only when justified (0–10)", "", { optional: true, type: "number" }), field("explanation", "Why does this evidence support that interpretation?", "", { type: "textarea", optional: true }), linkFields(state)[1]
    ], build: (data) => ({ type: "record_evidence", evidence: { id: fresh(), statement: get(data, "statement"), source: { kind: get(data, "kind"), reference: get(data, "reference"), url: optional(data, "url"), observedAt: get(data, "observedAt"), scope: get(data, "scope") }, direction: get(data, "direction"), reliability: get(data, "reliability"), opportunityId: optional(data, "opportunityId"), meetingId: selectedMeeting?.id, personId: selectedMeeting?.personId, dimension: optional(data, "dimension"), criterionId: optional(data, "criterionId"), score: get(data, "score") ? Number(get(data, "score")) : undefined, explanation: get(data, "explanation"), hypothesisIds: [...new Set([...(selectedMeeting?.hypothesisIds ?? []), ...(get(data, "hypothesisId") ? [get(data, "hypothesisId")] : [])])] } }) };
    case "requirement": return { ...common, title: "Resolve a qualification", description: "Use reviewed evidence from this opportunity. Anonymous discussion and inference cannot establish a requirement.", fields: [
      field("requirementId", "Requirement", "", { options: (selectedOpportunity?.requirements ?? []).map((item) => ({ value: item.id, label: item.label })) }), field("status", "Finding", "unknown", { options: [{ value: "unknown", label: "Still unresolved" }, { value: "met", label: "Requirement met" }, { value: "not_met", label: "Requirement not met" }] }), field("evidenceId", "Reviewed source", "", { optional: true, options: state.evidence.filter((item) => item.opportunityId === recordId && item.review === "accepted").map((item) => ({ value: item.id, label: item.statement })) })
    ], build: (data) => ({ type: "resolve_requirement", opportunityId: recordId, requirementId: get(data, "requirementId"), status: get(data, "status"), evidenceIds: get(data, "evidenceId") ? [get(data, "evidenceId")] : [] }) };
    case "decision": return { ...common, title: "Make the next decision", description: "Your judgment remains yours. Explain the next investment of time, or the reason to stop.", fields: [chooseOpportunity, field("decision", "My decision", "investigate", { options: options(["investigate", "pursue", "pause", "decline"]) }), field("rationale", "Why?", selectedOpportunity?.decision?.rationale, { type: "textarea" }), field("nextAction", "Next action, or what I am deliberately pausing", selectedOpportunity?.decision?.nextAction, { type: "textarea" }), field("revisitWhen", "What would cause me to reconsider?", selectedOpportunity?.decision?.revisitWhen), field("due", "Next-action date", "", { optional: true, type: "date" })], build: (data) => ({ type: "decide_opportunity", opportunityId: get(data, "opportunityId"), decision: get(data, "decision"), rationale: get(data, "rationale"), nextAction: get(data, "nextAction"), revisitWhen: get(data, "revisitWhen"), due: optional(data, "due") }) };
    case "person": return { ...common, title: selectedPerson ? "Review this relationship" : "Prepare a useful conversation", fields: [field("name", "Name", selectedPerson?.name), field("company", "Company", selectedPerson?.company, { optional: true }), field("role", "Role or perspective", selectedPerson?.role, { optional: true }), field("email", "Email, if known", selectedPerson?.email, { optional: true, type: "email" }), field("source", "How do you know about this person?", selectedPerson?.source), field("overlap", "Genuine shared context", selectedPerson?.overlap, { optional: true }), field("whyNow", "Why this person, now?", selectedPerson?.whyNow, { type: "textarea" }), field("objective", "What do you want to learn?", selectedPerson?.objective), field("introductionPath", "Introduction path", selectedPerson?.introductionPath, { optional: true }), field("nextTouch", "Next touch", selectedPerson?.nextTouch, { optional: true, type: "date" }), ...linkFields(state).map((item) => ({ ...item, value: item.name === "opportunityId" ? selectedPerson?.opportunityId : selectedPerson?.hypothesisIds[0] }))], build: (data) => ({ type: "save_person", person: { id: selectedPerson?.id ?? fresh(), name: get(data, "name"), company: get(data, "company"), role: get(data, "role"), email: optional(data, "email"), source: get(data, "source"), overlap: get(data, "overlap"), whyNow: get(data, "whyNow"), objective: get(data, "objective"), introductionPath: get(data, "introductionPath"), nextTouch: optional(data, "nextTouch"), opportunityId: optional(data, "opportunityId"), hypothesisIds: get(data, "hypothesisId") ? [get(data, "hypothesisId")] : [] } }) };
    case "meeting": return { ...common, title: selectedMeeting ? "Reconcile this meeting" : "Record an agreed meeting", description: "Record timing already agreed, or a planned conversation. This does not send a calendar invitation.", fields: [field("title", "Conversation", selectedMeeting?.title), field("personId", "Person", selectedMeeting?.personId ?? selectedPerson?.id, { optional: true, options: state.people.map((item) => ({ value: item.id, label: item.name })) }), field("kind", "Purpose", selectedMeeting?.kind ?? "networking", { options: options(["networking", "coaching", "interview", "mentor"]) }), field("startsAt", "Starts at (your local time)", selectedMeeting ? localTime(selectedMeeting.startsAt) : "", { type: "datetime-local" }), field("endsAt", "Ends at (your local time)", selectedMeeting ? localTime(selectedMeeting.endsAt) : "", { type: "datetime-local" }), field("status", "Meeting status", selectedMeeting?.status ?? "accepted", { options: options(["planned", "accepted", "cancelled"]) }), field("objective", "What should this conversation resolve?", selectedMeeting?.objective ?? selectedPerson?.objective), ...linkFields(state).map((item) => ({ ...item, value: item.name === "opportunityId" ? selectedMeeting?.opportunityId ?? selectedPerson?.opportunityId : selectedMeeting?.hypothesisIds[0] ?? selectedPerson?.hypothesisIds[0] }))], build: (data) => ({ type: "record_meeting", meeting: { id: selectedMeeting?.id ?? fresh(), title: get(data, "title"), personId: optional(data, "personId"), opportunityId: optional(data, "opportunityId"), hypothesisIds: get(data, "hypothesisId") ? [get(data, "hypothesisId")] : [], kind: get(data, "kind"), startsAt: new Date(get(data, "startsAt")).toISOString(), endsAt: new Date(get(data, "endsAt")).toISOString(), status: get(data, "status"), provider: selectedMeeting?.provider ?? "manual", sourceEventId: selectedMeeting?.sourceEventId, objective: get(data, "objective") } }) };
    case "debrief": return { ...common, title: "What changed in this conversation?", description: "Capture the useful learning. Add detailed evidence from the review after this debrief; it will not silently change your criteria.", fields: [field("said", "What was actually said?", "", { type: "textarea" }), field("inferred", "What do you infer from it?", "", { type: "textarea", optional: true }), field("unresolved", "Questions still open — one per line", "", { type: "textarea", optional: true }), field("introductions", "Introductions offered — one per line", "", { type: "textarea", optional: true }), field("promise", "My next commitment", "", { optional: true }), field("definitionOfDone", "How will I know that commitment is complete?", "", { optional: true }), field("due", "Commitment due", "", { optional: true, type: "date" }), field("nextTouch", "Next relationship touch", "", { optional: true, type: "date" })], build: (data) => ({ type: "debrief_meeting", meetingId: recordId, said: get(data, "said"), inferred: get(data, "inferred"), unresolved: lines(data, "unresolved"), introductions: lines(data, "introductions"), nextTouch: optional(data, "nextTouch"), evidence: [], commitments: get(data, "promise") ? [{ id: fresh(), title: get(data, "promise"), owner: "Fellow", due: optional(data, "due"), definitionOfDone: get(data, "definitionOfDone"), reviewTrigger: "If the agreed follow-through becomes blocked" }] : [] }) };
    case "hypothesis": return { ...common, title: "Review a possible direction", fields: [field("proposition", "Direction to test", selectedHypothesis?.proposition), field("whyPromising", "Why might it fit?", selectedHypothesis?.whyPromising, { type: "textarea" }), field("assumptions", "Assumptions — one per line", selectedHypothesis?.assumptions.join("\n"), { type: "textarea", optional: true }), field("gaps", "Skill or evidence gaps — one per line", selectedHypothesis?.gaps.join("\n"), { type: "textarea", optional: true }), field("confidenceExplanation", "What supports your current confidence?", selectedHypothesis?.confidenceExplanation, { type: "textarea" }), field("nextExperiment", "Next experiment", selectedHypothesis?.nextExperiment), field("reviewTrigger", "When or why should you review it?", selectedHypothesis?.reviewTrigger), field("status", "Direction decision", selectedHypothesis?.status ?? "continue", { options: options(["continue", "refine", "split", "pause", "reject"]) })], build: (data) => ({ type: "save_hypothesis", hypothesis: hypothesisValue(data, selectedHypothesis?.id ?? fresh()) }) };
    case "criteria": {
      const criterion = state.criteria.find((item) => item.id === recordId);
      return { ...common, title: criterion ? "Revisit a criterion" : "Confirm a criterion", description: "Changing a criterion can change the recommendation. Earlier decisions and evidence remain in the history.", fields: [field("label", "Criterion", criterion?.label), field("desired", "What would good look like?", criterion?.desired, { type: "textarea" }), field("dimension", "Relevant part of fit", criterion?.dimension ?? "environment", { options: Object.entries(DIMENSIONS).map(([value, label]) => ({ value, label })) }), field("importance", "Importance (1–5)", String(criterion?.importance ?? 3), { type: "number" }), field("nonNegotiable", "Is this a non-negotiable?", String(criterion?.nonNegotiable ?? false), { options: [{ value: "false", label: "Preference to weigh" }, { value: "true", label: "Non-negotiable" }] }), field("reason", "Why confirm or change this now?", "", { type: "textarea" })], build: (data) => ({ type: "confirm_criteria", criteria: [...state.criteria.filter((item) => item.id !== criterion?.id), { id: criterion?.id ?? fresh(), label: get(data, "label"), desired: get(data, "desired"), dimension: get(data, "dimension"), importance: Number(get(data, "importance")), nonNegotiable: get(data, "nonNegotiable") === "true", confirmed: true }], reason: get(data, "reason") }) };
    }
    case "promise": return { ...common, title: "Keep a commitment", fields: [field("title", "What did you agree to do?"), field("owner", "Who owns it?", "Fellow"), field("definitionOfDone", "Evidence of completion", "", { type: "textarea" }), field("reviewTrigger", "When should this be reconsidered?"), field("due", "Due", "", { type: "date", optional: true }), ...linkFields(state)], build: (data) => ({ type: "save_commitment", commitment: { id: fresh(), title: get(data, "title"), owner: get(data, "owner"), definitionOfDone: get(data, "definitionOfDone"), reviewTrigger: get(data, "reviewTrigger"), due: optional(data, "due"), opportunityId: optional(data, "opportunityId"), hypothesisId: optional(data, "hypothesisId") } }) };
    case "resolve-promise": return { ...common, title: "What happened with this commitment?", fields: [field("status", "Current result", "done", { options: options(["done", "blocked", "cancelled"]) }), field("evidence", "What proves completion, or explains the change?", "", { type: "textarea" })], build: (data) => ({ type: "resolve_commitment", commitmentId: recordId, status: get(data, "status"), evidence: get(data, "evidence") }) };
    case "weekly": return { ...common, title: "Change next week", description: "A useful review changes behavior. Use your reviewed evidence and conversations to decide what deserves your time.", fields: [field("learned", "What did you learn about the work you want?", "", { type: "textarea" }), field("start", "What will you start?"), field("stop", "What will you stop?"), field("change", "What will you change?", "", { type: "textarea" })], build: (data) => ({ type: "review_week", learned: get(data, "learned"), start: get(data, "start"), stop: get(data, "stop"), change: get(data, "change"), hypothesisUpdates: [], commitments: [] }) };
    case "story": return { ...common, title: "Keep the evidence of your contribution", fields: [field("title", "Story title"), field("situation", "Situation", "", { type: "textarea" }), field("contribution", "Your actual contribution", "", { type: "textarea" }), field("scope", "Scope and limits of your authority"), field("actions", "What you did", "", { type: "textarea" }), field("outcome", "What changed", "", { type: "textarea" }), field("skills", "Skills demonstrated — one per line", "", { type: "textarea" }), field("approvedLanguage", "Truthful wording you approve for reuse", "", { type: "textarea" }), field("uncertainNumbers", "Numbers or claims still unverified", "", { optional: true, type: "textarea" }), field("evidenceId", "Reviewed supporting evidence", "", { options: state.evidence.filter((item) => item.review === "accepted").map((item) => ({ value: item.id, label: item.statement })) })], build: (data) => ({ type: "save_story", story: { id: fresh(), title: get(data, "title"), situation: get(data, "situation"), contribution: get(data, "contribution"), scope: get(data, "scope"), actions: get(data, "actions"), outcome: get(data, "outcome"), skills: lines(data, "skills"), approvedLanguage: get(data, "approvedLanguage"), uncertainNumbers: lines(data, "uncertainNumbers"), evidenceIds: [get(data, "evidenceId")], confirmed: true } }) };
    case "material": return { ...common, title: "Preserve a material version", description: "Paste the reviewed text of a résumé, profile, cover letter, or work sample. New versions do not change what was previously submitted.", fields: [chooseOpportunity, field("kind", "Material", "resume", { options: options(["resume", "cover_letter", "profile", "work_sample"]) }), field("title", "Version title"), field("content", "Exact reviewed text", "", { type: "textarea" }), field("storyId", "Evidence used", "", { optional: true, options: state.stories.map((item) => ({ value: item.id, label: item.title })) })], submit: "Confirm truthful wording and save version", build: (data) => ({ type: "save_material", material: { id: fresh(), opportunityId: get(data, "opportunityId"), kind: get(data, "kind"), title: get(data, "title"), content: get(data, "content"), storyIds: get(data, "storyId") ? [get(data, "storyId")] : [], confirmedTruthful: true } }) };
    case "submission": return { ...common, title: "Record an actual submission", description: "Only continue after you actually submitted. Saving materials or approving a draft is not an application.", fields: [field("materialId", "Exact version submitted", "", { options: state.materials.filter((item) => item.opportunityId === recordId).map((item) => ({ value: item.id, label: item.title + " · version " + item.version })) }), field("submittedAt", "When you submitted (local time)", "", { type: "datetime-local" }), field("receipt", "Submission confirmation or your explicit account", "", { type: "textarea" })], submit: "Confirm I submitted this version", build: (data) => ({ type: "record_submission", opportunityId: recordId, materialIds: [get(data, "materialId")], submittedAt: new Date(get(data, "submittedAt")).toISOString(), receipt: get(data, "receipt"), confirmedSubmitted: true }) };
    case "application-outcome": return { ...common, title: "What happened with this application?", description: "Keep actual employer feedback distinct from your interpretation. The next step becomes a commitment you can resume.", fields: [chooseOpportunity, field("outcome", "Result", "rejected", { options: options(["rejected", "withdrawn", "interview", "offer"]) }), field("reason", "What happened, and what did you learn?", "", { type: "textarea" }), field("source", "Source of this result"), field("nextAction", "What will you do differently or follow through on?", "", { type: "textarea" })], build: (data) => ({ type: "record_application_outcome", opportunityId: get(data, "opportunityId"), outcome: get(data, "outcome"), reason: get(data, "reason"), source: get(data, "source"), nextAction: get(data, "nextAction") }) };
    case "interview": return { ...common, title: "Make this interview improve the next", fields: [chooseOpportunity, field("round", "Interview round"), field("interviewerContext", "Known interviewer context", "", { optional: true }), field("questionsAsked", "Questions actually asked — one per line", "", { type: "textarea" }), field("storyId", "Story you used", "", { optional: true, options: state.stories.map((item) => ({ value: item.id, label: item.title })) }), field("missingExamples", "Examples you needed — one per line", "", { type: "textarea", optional: true }), field("selfAssessment", "Your self-assessment", "", { type: "textarea" }), field("employerFeedback", "Actual employer feedback", "", { type: "textarea", optional: true }), field("employerFeedbackSource", "Source of that employer feedback", "", { optional: true }), field("nextPreparation", "What will you prepare differently next time?", "", { type: "textarea" })], build: (data) => ({ type: "record_interview", interview: { id: fresh(), opportunityId: get(data, "opportunityId"), round: get(data, "round"), interviewerContext: get(data, "interviewerContext"), questionsAsked: lines(data, "questionsAsked"), storyIds: get(data, "storyId") ? [get(data, "storyId")] : [], missingExamples: lines(data, "missingExamples"), selfAssessment: get(data, "selfAssessment"), employerFeedback: get(data, "employerFeedback"), employerFeedbackSource: optional(data, "employerFeedbackSource"), nextPreparation: get(data, "nextPreparation"), evidence: [] } }) };
    case "offer": return { ...common, title: "Examine an offer", description: "Record what is known, then compare tradeoffs against your criteria. Estimated and unknown terms stay visible.", fields: [chooseOpportunity, field("terms", "Offer terms", "", { type: "offer-terms" }), field("deadline", "Decision deadline", "", { type: "date", optional: true }), field("tradeoffs", "Tradeoffs that matter", "", { type: "textarea" }), field("unresolvedQuestions", "Unresolved questions — one per line", "", { type: "textarea", optional: true }), field("negotiationPriorities", "Negotiation priorities — one per line", "", { type: "textarea", optional: true }), field("recruitingPromises", "Promises made during recruiting — one per line", "", { type: "textarea", optional: true })], build: (data) => ({ type: "record_offer", offer: { id: fresh(), opportunityId: get(data, "opportunityId"), deadline: optional(data, "deadline"), terms: data.getAll("termLabel").map((label, index) => ({ label: String(label), value: String(data.getAll("termValue")[index]), certainty: String(data.getAll("termCertainty")[index]), source: String(data.getAll("termSource")[index]) })), tradeoffs: get(data, "tradeoffs"), unresolvedQuestions: lines(data, "unresolvedQuestions"), negotiationPriorities: lines(data, "negotiationPriorities"), recruitingPromises: lines(data, "recruitingPromises") } }) };
    case "accept-offer": return { ...common, title: "Carry the decision into your new work", description: "Record an acceptance you have actually made. This sends nothing to an employer.", fields: [field("rationale", "Why did you accept?", "", { type: "textarea" }), field("startDate", "Start date", "", { type: "date" }), field("day30", "Day 30: manager alignment and learning evidence", "", { type: "textarea" }), field("day60", "Day 60: stakeholder relationships and contribution evidence", "", { type: "textarea" }), field("day90", "Day 90: value delivered and next learning question", "", { type: "textarea" })], submit: "Confirm acceptance and preserve the plan", build: (data) => ({ type: "accept_offer", offerId: recordId, rationale: get(data, "rationale"), confirmedAccepted: true, startDate: get(data, "startDate"), checkpoints: [30, 60, 90].map((day) => ({ id: fresh(), day, title: "Day " + day + " checkpoint", successEvidence: get(data, "day" + day), owner: "Fellow" })) }) };
    case "close-chapter": return { ...common, title: "Continue beyond transition", fields: [field("reflection", "What changed, and what should you carry forward?", "", { type: "textarea" }), field("nextFocus", "What deserves attention in your professional work?", "", { type: "textarea" }), field("carryForward", "Choose what to carry into the next chapter", "", { multiple: true, optional: true, help: "Select the useful relationships, examples, directions, and commitments. Your full transition history remains available.", options: [...state.stories.map((item) => ({ value: item.id, label: "Example: " + item.title })), ...state.people.map((item) => ({ value: item.id, label: "Person: " + item.name })), ...state.hypotheses.map((item) => ({ value: item.id, label: "Direction: " + item.proposition })), ...state.commitments.filter((item) => ["open", "blocked"].includes(item.status)).map((item) => ({ value: item.id, label: "Commitment: " + item.title }))] })], description: "Your transition history remains available. Existing stories, relationships, hypotheses, and open commitments stay linked to this chapter.", build: (data) => ({ type: "close_chapter", reflection: get(data, "reflection"), nextFocus: get(data, "nextFocus"), carryForward: data.getAll("carryForward").map(String).filter(Boolean) }) };
    case "action": return { ...common, title: "Review the exact draft", description: "Edit what the recipient will see. Saving a revision invalidates any previous approval; it does not send.", fields: [field("recipient", "Recipient", selectedAction?.recipient), field("subject", "Subject", selectedAction?.subject), field("body", "Message", selectedAction?.body, { type: "textarea" })], build: (data) => ({ type: "revise_action", actionId: recordId, recipient: get(data, "recipient"), subject: get(data, "subject"), body: get(data, "body") }) };
    case "action-result": return { ...common, title: "Verify what happened", description: "Check your mail or calendar before recording the result. An uncertain result must not be retried blindly.", fields: [field("outcome", "Execution result", "manually_completed", { options: options(selectedAction?.state === "uncertain" ? ["manually_completed"] : ["manually_completed", "failed", "uncertain"]) }), field("receipt", "What did you verify?", "", { type: "textarea" })], build: (data) => ({ type: "record_action_result", actionId: recordId, outcome: get(data, "outcome"), receipt: get(data, "receipt") }) };
  }
}

export function localTime(iso: string) { const value = new Date(iso); return new Date(value.valueOf() - value.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export function WorkflowEditor({ intent, state, recordId, onSave, onClose }: { intent: Intent; state: PilotState; recordId?: string; onSave: (command: Command) => Promise<void>; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState("");
  const config = definition(intent, state, recordId);
  useEffect(() => { dialog.current?.showModal(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setPending(true);
    try { const command = commandSchema.parse(config.build(new FormData(event.currentTarget))); await onSave(command); onClose(); }
    catch (caught) { setError(caught instanceof Error ? ("issues" in caught ? "Review the required fields and their formats. Use complete, ordinary transition information." : caught.message) : "This step could not be verified."); }
    finally { setPending(false); }
  }
  return <dialog ref={dialog} className={styles.dialog} onCancel={(event) => { if (pending) event.preventDefault(); else onClose(); }} aria-labelledby="workflow-title">
    <header className={styles.dialogHeader}><div><span className={styles.eyebrow}>SOTF Bundle</span><h2 id="workflow-title">{config.title}</h2></div><button type="button" disabled={pending} onClick={onClose} aria-label="Close review">×</button></header>
    <p>{config.description}</p>
    <form className={styles.form} onSubmit={(event) => void submit(event)}>
      {config.fields.map((item) => item.type === "offer-terms" ? <OfferTerms key={item.name} /> : <label key={item.name}>{item.label}{item.optional ? <small>Optional</small> : null}
        {item.options ? <select name={item.name} multiple={item.multiple} required={!item.optional} defaultValue={item.multiple ? [] : item.value ?? ""}><option value="">{item.optional ? "None selected" : "Choose…"}</option>{item.options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>
          : item.type === "textarea" ? <textarea name={item.name} required={!item.optional} defaultValue={item.value} rows={4} maxLength={item.name === "description" ? 24000 : 5000} />
          : <input name={item.name} required={!item.optional} type={item.type ?? "text"} defaultValue={item.value} maxLength={item.name === "url" ? 2000 : 240} />}
        {item.help ? <span className={styles.help}>{item.help}</span> : null}
      </label>)}
      {error ? <p className={styles.error} role="alert">{error}</p> : null}
      <footer className={styles.formActions}><button type="button" disabled={pending} onClick={onClose}>Cancel</button><button className={styles.primary} disabled={pending}>{pending ? "Verifying…" : config.submit}</button></footer>
    </form>
  </dialog>;
}

function OfferTerms() {
  const [rows, setRows] = useState([0]);
  const sequence = useRef(0);
  return <fieldset><legend>Offer terms and their evidence</legend>{rows.map((row, index) => <fieldset key={row}><legend>Term {index + 1}</legend>
    <label>Term<input name="termLabel" required maxLength={240} placeholder="Travel, manager, compensation, learning…" /></label>
    <label>Value<textarea name="termValue" required maxLength={5000} rows={2} /></label>
    <label>How certain is it?<select name="termCertainty" defaultValue="reported"><option value="written">Written</option><option value="reported">Reported</option><option value="estimated">Estimated</option><option value="unknown">Unknown</option></select></label>
    <label>Source<input name="termSource" required maxLength={240} placeholder="Offer letter, recruiter conversation, or not supplied" /></label>
    {rows.length > 1 ? <button type="button" onClick={() => setRows(rows.filter((value) => value !== row))}>Remove this term</button> : null}
  </fieldset>)}<button type="button" disabled={rows.length >= 25} onClick={() => { sequence.current += 1; setRows([...rows, sequence.current]); }}>Add another term</button></fieldset>;
}
