import {useState,useSyncExternalStore} from "react";
import type {ExecutiveDeliveryDefinition,ExecutiveDeliveryEvent,ExecutiveDeliverySchedule} from "../../../vendor/lead-emergence-bundles/domain-contracts/executive-delivery";

const workspaceId="91000000-0000-4000-8000-000000000003",now="2026-09-10T18:00:00.000Z";let sequence=1;
let value={schemaVersion:"1.0" as const,workspaceId,authorityRevision:"isolated-component",serverNow:now,schedules:[] as ExecutiveDeliverySchedule[],deliveries:[] as ExecutiveDeliveryEvent[],backgroundDeliveryAvailable:false as const};
const listeners=new Set<()=>void>();function publish(){for(const listener of listeners)listener();}function subscribe(listener:()=>void){listeners.add(listener);return()=>listeners.delete(listener);}function snapshot(){return value;}
function scheduleId(){return `91000000-0000-4000-8000-${String(sequence++).padStart(12,"0")}`;}
function next(definition:ExecutiveDeliveryDefinition){return definition.deliveryKind==="daily_brief"?"2026-09-11T12:30:00.000Z":"2026-09-11T21:00:00.000Z";}
export function useExecutiveRead<T>(){const data=useSyncExternalStore(subscribe,snapshot,snapshot);return {enabled:true,key:"isolated",data:data as T,error:null,loading:false,retry:()=>publish()};}
export function useExecutiveAction(){const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);return {busy,error,run:async<T,>(_path:string,input:any)=>{setBusy(true);setError(null);await Promise.resolve();let result:ExecutiveDeliverySchedule;
  if(input.operation==="create"){const stamp=new Date(Date.parse(now)+sequence*1000).toISOString();result={scheduleId:scheduleId(),version:1,definition:input.definition,status:"active",capabilityAvailable:true,nextOccurrence:next(input.definition),lastEvaluatedAt:null,lastDeliveredAt:null,createdAt:stamp,updatedAt:stamp,replayed:false};value={...value,schedules:[result,...value.schedules]};}
  else {const current=value.schedules.find(schedule=>schedule.scheduleId===input.scheduleId)!;const status=input.operation==="pause"?"paused":input.operation==="resume"?"active":input.operation==="cancel"?"cancelled":current.status;const definition=input.operation==="update"?input.definition:current.definition;result={...current,definition,status,version:current.version+1,nextOccurrence:status==="active"?next(definition):null,updatedAt:new Date(Date.parse(now)+(sequence++)*1000).toISOString(),replayed:false};value={...value,schedules:value.schedules.map(schedule=>schedule.scheduleId===result.scheduleId?result:schedule)};}
  publish();setBusy(false);return result as T;}};}
export function simulateDue(){const schedule=value.schedules.find(item=>item.status==="active");if(!schedule)return;const evaluated="2026-09-11T14:00:00.000Z",updated={...schedule,nextOccurrence:"2026-09-12T12:30:00.000Z",lastEvaluatedAt:evaluated,lastDeliveredAt:evaluated,updatedAt:evaluated};value={...value,schedules:value.schedules.map(item=>item.scheduleId===schedule.scheduleId?updated:item),deliveries:[{deliveryId:"92000000-0000-4000-8000-000000000001",scheduleId:schedule.scheduleId,scheduleVersion:schedule.version,deliveryKind:schedule.definition.deliveryKind,label:schedule.definition.label,dueAt:schedule.nextOccurrence!,evaluatedAt:evaluated,outcome:"ready" as const,reason:"The scheduled native review is ready. Review current saved-work cues; no record was created or sent.",currentAttentionCount:63,inspectedAttentionCount:50,inspectedHighPriorityCount:7,route:(schedule.definition.deliveryKind==="daily_brief"?"/workspace/executive/daily_brief/new":"/workspace/executive/weekly_review/new") as "/workspace/executive/daily_brief/new",requiresUserReview:true as const,externalDelivery:false as const,recordCreated:false as const}],serverNow:evaluated};publish();}
